# Maven
# Build your Java projects and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/java

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  - group: stacktech
  
steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: settings_azure

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.10'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: "clean install"
    #goals: "-Dsonar.login=$(SONAR_LOGIN_TOKEN) --settings $(Agent.TempDirectory)/settings_azure verify sonar:sonar deploy"
    #goals: '-Dsonar.login=$(SONAR_LOGIN_TOKEN) --settings settings.xml verify sonar:sonar deploy'
